export const popularCarData = [
  {
    like: true,
    name: "Koenigsegg",
    category: "Sport",
    imageURL: "/images/Koenigsegg.png",
    gasoline: 90,
    carType: "Manual",
    peopleCapacity: 2,
    price: "99.00",
    discount: false,
    discountOldPrice: null,
  },
  {
    like: false,
    name: "Nissan GT - R",
    category: "Sport",
    imageURL: "/images/Nissan-GT-R.png",
    gasoline: 80,
    carType: "Manual",
    peopleCapacity: 2,
    price: "80.00",
    discount: true,
    discountOldPrice: "100.00",
  },
  {
    like: true,
    name: "Rolls - Royce",
    category: "Sedan",
    imageURL: "/images/Rolls-Royce.png",
    gasoline: 70,
    carType: "Manual",
    peopleCapacity: 4,
    price: "96.00",
    discount: false,
    discountOldPrice: null,
  },
  {
    like: false,
    name: "Nissan GT - R",
    category: "Sport",
    imageURL: "/images/Nissan-GT-R.png",
    gasoline: 80,
    carType: "Manual",
    peopleCapacity: 2,
    price: "80.00",
    discount: true,
    discountOldPrice: "100.00",
  },
];

export const recommendCarData = [
  {
    like: false,
    name: "All New Rush",
    category: "SUV",
    imageURL: "/images/All-New-Rush.png",
    gasoline: 70,
    carType: "Manual",
    peopleCapacity: 6,
    price: "72.00",
    discount: true,
    discountOldPrice: "80.00",
  },
  {
    like: true,
    name: "CR - V",
    category: "SUV",
    imageURL: "/images/CR-V-1.png",
    gasoline: 80,
    carType: "Manual",
    peopleCapacity: 6,
    price: "80.00",
    discount: false,
    discountOldPrice: null,
  },
  {
    like: false,
    name: "All New Terios",
    category: "SUV",
    imageURL: "/images/All-New-Terios.png",
    gasoline: 90,
    carType: "Manual",
    peopleCapacity: 6,
    price: "74.00",
    discount: false,
    discountOldPrice: null,
  },
  {
    like: true,
    name: "CR - V",
    category: "SUV",
    imageURL: "/images/CR-V-2.png",
    gasoline: 80,
    carType: "Manual",
    peopleCapacity: 6,
    price: "80.00",
    discount: false,
    discountOldPrice: null,
  },
  {
    like: true,
    name: "MG ZX Exclusive",
    category: "Hatchback",
    imageURL: "/images/MG-ZX-Exclusive.png",
    gasoline: 70,
    carType: "Manual",
    peopleCapacity: 4,
    price: "76.00",
    discount: true,
    discountOldPrice: "80.00",
  },
  {
    like: false,
    name: "New MG ZS",
    category: "SUV",
    imageURL: "/images/New-MG-ZS.png",
    gasoline: 80,
    carType: "Manual",
    peopleCapacity: 6,
    price: "80.00",
    discount: false,
    discountOldPrice: null,
  },
  {
    like: true,
    name: "MG ZX Excite",
    category: "Hatchback",
    imageURL: "/images/MG-ZX-Excite.png",
    gasoline: 90,
    carType: "Manual",
    peopleCapacity: 4,
    price: "74.00",
    discount: false,
    discountOldPrice: null,
  },
  {
    like: false,
    name: "New MG ZS",
    category: "SUV",
    imageURL: "/images/New-MG-ZS.png",
    gasoline: 80,
    carType: "Manual",
    peopleCapacity: 6,
    price: "80.00",
    discount: false,
    discountOldPrice: null,
  },
];
